# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :sut do |sut|
    sut.vm.box = "bento/ubuntu-20.04"
    sut.vm.hostname = "SageSUT"
    sut.vm.synced_folder "../../../..", "/sage"
    sut.vm.network :private_network, ip: "10.0.0.10"
    sut.vm.provider "virtualbox" do |vb|
      vb.name = "SageSUT"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "1"
    end
    sut.vm.provision "deps", type: "shell", privileged: false, inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y \
           build-essential \
           python3-pip \
           clang-format \
           libsqlite3-dev \
           libpcap-dev \
           libnetfilter-queue-dev \
           git
    SHELL
    sut.vm.provision "pydeps", type: "shell", privileged: false, inline: <<-SHELL
      pip3 install --no-cache-dir \
           tabulate \
           tqdm \
           torch \
           termcolor \
           networkx \
           matplotlib \
           pydot \
           nltk \
           stanfordcorenlp \
           "spacy >=2.2,<3"
    SHELL
    sut.vm.provision "spacy", type: "shell", privileged: false, inline: <<-SHELL
      python3 -m spacy download en
    SHELL
    sut.vm.provision "neuralcoref", type: "shell", privileged: false, inline: <<-SHELL
      git clone --depth 1 https://github.com/huggingface/neuralcoref.git
      cd neuralcoref
      pip3 install -r requirements.txt
      pip3 install -e .
    SHELL
    sut.vm.provision "nltk", type: "shell", privileged: false, inline: <<-SHELL
      sed -i \
      "s/for edge in self.select(start=0, end=self._num_leaves, lhs=root):/for edge in self.select(start=0, end=self._num_leaves):/" \
      ~/.local/lib/python3.*/site-packages/nltk/parse/chart.py
    SHELL
    sut.vm.provision "clean", type: "shell", privileged: false, inline: <<-SHELL
      sudo apt-get clean
    SHELL
    sut.vm.provision "link", type: "shell", privileged: false, inline: <<-SHELL
      ln -s /sage ~/sage
    SHELL
  end

  ########
  # TESTER
  config.vm.define :tester do |tester|
    tester.vm.box = "bento/ubuntu-20.04"
    tester.vm.hostname = "SageTester"
    tester.vm.network :private_network, ip: "10.0.0.11"
    tester.vm.provider "virtualbox" do |vb|
      vb.name = "SageTester"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "1"
    end
    tester.vm.provision "deps", type: "shell", privileged: false, inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y \
           traceroute
    SHELL
    tester.vm.provision "clean", type: "shell", privileged: false, inline: <<-SHELL
      sudo apt-get clean
    SHELL
  end
end
